title: Sébastien Saunier

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
pygments: true
lsi: false
markdown: redcarpet

# Keybase
include:
  - .well-known

# White-listed plugins
gems:
  - jekyll-sitemap